version: 1.0.{build}

branches:
  only:
  - master

skip_tags: true
clone_folder: c:\projects\AirWaves

image: Visual Studio 2015

environment:
  matrix:
    - BUILD_MODE: Debug
    - BUILD_MODE: Release

matrix:
  fast_finish: true

platform: x64

build:
  parallel: true  # enable MSBuild parallel builds
  verbosity: minimal

build_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPES=%BUILD_TYPE% -DBUILD_TESTS=ON ..
  - cmake --build . --config %BUILD_TYPE% -- /m
  - %BUILD_TYPE%\vmp-tests.exe

