language: c++

branches:
  only:
    - master

dist: trusty
os: osx

install:
  ############################################################################
  # Install a recent CMake
  ############################################################################
  - brew update
  - brew outdated <package-name> || brew upgrade <package-name>
  - cmake --version

script:
  - mkdir cmake-build-debug
  - cd cmake-build-debug
  - cmake -DCMAKE_BUILD_TYPE=Debug -DVMP_BUILD_TESTS=ON ..
  - make -j
  - ./vmp-tests
  - cd ..

  - mkdir cmake-build-release
  - cd cmake-build-release
  - cmake -DCMAKE_BUILD_TYPE=Release -DVMP_BUILD_TESTS=ON ..
  - make -j
  - ./vmp-tests
  - cd ..


notifications:
  on_success: never
  on_failure: always
